import "./globals.css";

import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";

import StoreProvider from "@/redux-lib/StoreProvider";
import { CounterStoreProvider } from "@/zustand-context-lib/CounterStoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Override 65ch max-width in Tailwind CSS Typography
// https://stackoverflow.com/questions/74914969

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="prose prose-sm !max-w-none">
        <StoreProvider>
          <CounterStoreProvider>
            <NextUIProvider>
              {children}
            </NextUIProvider>
          </CounterStoreProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
