import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";

import "./globals.css";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Override 65ch max-width in Tailwind CSS Typography
// https://stackoverflow.com/questions/74914969

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="prose prose-sm !max-w-none">
        <StoreProvider>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
